- hosts: database
  gather_facts: true
  tasks:

  - name: confirm sqldump binaries 
    apt:
     pkg:
      - python3-pip
      - python3-mysqldb
  - name: install prequisites
    pip:
      name:
        - PyMySQL
        - MySQL-python
      executable: pip3

  - name: backup db
    mysql_db:
      state: dump
      name: all
      target: /tmp/tmp/backup.sql
      force: yes

  - name: copy sql backup to local machine 
    fetch:
      src: /tmp/backup.sql
      dest: ./
    
