- hosts: database
  gather_facts: true
  tasks:

  - name: confirm sqldump binaries 
    apt:
     pkg:
      - python3-pip

  - name: install prequisites
    pip:
      exectutable: pip3
      name:
        - PyMySQL
        - MySQLdb 

  - name: backup db
    mysql_db:
      state: dump
      name: all
      target: /tmp//tmp/backup.sql
      force: yes

  - name: copy sql backup to local machine 
    fetch:
      src: /tmp//tmp/backup.sql
      dest: ./
    
