- hosts: all
  gather_facts: true
  tasks:
  - name: create cron entry 
    cron:
     name: "php cron"
     minute:  "*"
     hour: "*"
     job: "php /var/www/html/artisan schedule:run >> /dev/null 2>&1" 